version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - /Users/muttakin/Developer/Playground/Database/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s

  node_server:
    build: .
    container_name: node_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: user_db
