version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - /Users/muttakin/Developer/Playground/Database/mysql_data:/var/lib/mysql
